# -*- coding: utf-8 -*-
{'application': True,
 'author': 'MTDN',
 'category': 'MTDN',
 'data': ['security/ir.model.access.csv',
          'data/sequence.xml',
          'data/seed.xml',
          'views/maintenance_category_views.xml',
          'views/maintenance_team_views.xml',
          'views/maintenance_request_views.xml',
          'views/asset_inherit_views.xml',
          'views/room_inherit_views.xml',
          'views/maintenance_menu.xml'],
 'demo': ['demo/demo.xml'],
 'depends': ['base', 'web', 'mtdn_asset', 'mtdn_meeting', 'mtdn_hr'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'MTDN - Bảo trì (Maintenance + Downtime)',
 'summary': 'Phiếu bảo trì cho phòng họp và tài sản, có downtime và chặn đặt lịch khi bảo trì.',
 'version': '19.0.1.0.0'}
